### ISSUE TITLE
본문 길이 초과 작성 시 에러 

### ISSUE THREAD

**Issue by kkkapuq** [Kernel360/E2E1-Boogle#151]
**버그 내용**
- 본문 길이를 초과해서 작성하면 에러가 발생

**발생한 상황**
- 3159자로 테스트해봤습니다.

**정상 동작 (예상한 결과)**
- 글자수 초과 에러가 뜨는게 좋을것같습니다.

**스크린샷**
- 
![image](https://github.com/Kernel360/E2E1-Boogle/assets/44130863/c083e71c-f90b-4b6f-8ddf-8da8671efc27)

**Comment by linglong67** [comment]
DB 컬럼 확인 후 수정함 (기존에 세팅한 컬럼 정보가 변경되어있었음.)
