### ISSUE TITLE
댓글 없는 상태로 [내가 쓴 댓글보기] 버튼 누르면 500 에러 발생

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/E2E1-Boogle#156]
**버그 내용**
- 댓글 없는 상태로 마이페이지에서 [내가 쓴 댓글보기] 버튼 누르면 500 에러 발생합니다!!!

**발생한 상황**
- 댓글 없는 상태로 마이페이지에서 [내가 쓴 댓글보기] 버튼 누르면 500 에러 발생합니다!!!

**정상 동작 (예상한 결과)**
- 댓글 없는 상태로 마이페이지에서 [내가 쓴 댓글보기] 버튼 누르면 작성한 댓글이 없다 같은 이벤트가 발생할 것으로 예상하였으나 500에러발생

**스크린샷**
<img width="1293" alt="스크린샷 2023-11-22 오전 11 36 57" src="https://github.com/Kernel360/E2E1-Boogle/assets/59242594/134b280d-17ae-4883-b6f4-811a81581044">

<img width="613" alt="image" src="https://github.com/Kernel360/E2E1-Boogle/assets/59242594/38c745e4-20ba-4762-a56d-5ca947323b42">

**비고**

**Comment by cgk95** [comment]
내가 쓴 댓글 있는 상태에서도 발생합니다
## 댓글 작성한 화면
![image](https://github.com/Kernel360/E2E1-Boogle/assets/73059667/976004f8-eced-4eb1-aa2d-af833ffcfa5e)
<br>
## 내가 쓴 댓글보기 클릭 시 화면
![image](https://github.com/Kernel360/E2E1-Boogle/assets/73059667/22dbdcb4-91a5-4cec-9ef2-8bdadd7cef31)

**Comment by linglong67** [comment]
내가 쓴 댓글로 이동하는 기능이 필요하지 않을 것 같아 버튼 기능 제외시켰습니다
