### ISSUE TITLE
내가 쓴 독후감 조회되지 않음.

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/E2E1-Boogle#158]
**버그 내용**
- 마이페이지에서 [내가 쓴 독후감] 버튼을 눌르면 독후감이 보이지 않습니다 !!

**발생한 상황**
- 마이페이지에서 [내가 쓴 독후감] 버튼을 눌르면 독후감이 보이지 않습니다 !!

**정상 동작 (예상한 결과)**
- 마이페이지에서 [내가 쓴 독후감] 버튼을 눌르면 독후감이 보일 것으로 예상되었음.

**스크린샷**
<img width="1301" alt="image" src="https://github.com/Kernel360/E2E1-Boogle/assets/59242594/74752eaf-1830-45bb-b202-7de38e97b123">

**Comment by linglong67** [comment]
버튼 기능 없앰
