### ISSUE TITLE
[BUG] 내가 쓴 독후감 페이지에 접속시 이미지 파일 깨짐 문제

### ISSUE THREAD

**Issue by cgk95** [Kernel360/E2E1-Boogle#160]
**버그 내용**
- 마이페이지에서 내가 쓴 독후감 페이지에 접속 시 결과 페이지의 이미지 파일이 깨짐 니다

**발생한 상황**
- 내가 쓴 독후감이 없을 때 
- 마이페이지에서 내가 쓴 독후감 버튼을 클릭
- 이동한 화면 중앙의 이미지가 로딩되지 않음

**정상 동작 (예상한 결과)**
- 이미지 깨짐 없는 화면

**스크린샷**
## 마이페이지
![image](https://github.com/Kernel360/E2E1-Boogle/assets/73059667/aa372b99-77de-4c61-8dcc-89523eb4e686)
<br>
## 이후 결과 페이지
![image](https://github.com/Kernel360/E2E1-Boogle/assets/73059667/b89e8c26-7beb-46a4-b61f-cc8b16c33e1e)
<br>

**비고**
- Whale 브라우저에서 실행하였습니다.

**Comment by linglong67** [comment]
해결완료
